#!/usr/bin/env python3
import subprocess
def execute(command):
        return subprocess.check_output(['bash' , '-c' , command])
def nmap_scan(ip_scan):
        print(" ")
        print("running nmap .....")
        res=execute(f'nmap -T4  {ip_scan} | grep "open" ').decode('utf-8').splitlines()
        ports = []
        print(20*" +_+")
        for port in res :
                print(port)
                port=port.split("/")[0]
                ports.append(port)
        port_list=".".join(ports)
        #print(port_list)
        print(20*" +_+")
        print("Do you want to check all ports or a specific port ")
        print("\n 1- All ports")
        print(" 2- A specific port")
        print(" 0- to exit")
        print(" ")
        choice_port=int(input("choose one of these options : "))

        if choice_port == 1 :
                name_file=input("choose name of file for output : ")
                for i in port_list.split("."):
                        #print(i)
                        execute(f'nmap -T4 -A -sV -oN {name_file}.txt -p {i} {ip_scan}')
                print(f"your scan is saved in {name_file}.txt")
        elif choice_port == 2 :
                num_port=input("enter the number of port : ")
                name_file=input("choose name of file for output : ")
                execute(f'nmap -T4 -A -sV -oN {name_file}.txt -p {num_port} {ip_scan}')
                print(f"your scan is saved in {name_file}.txt")
        elif choice_port==0:
                exit()

print(execute('clear').decode('utf-8'))
print(f"{16*' '} scan your network {13* ' '}")
print(53*"-")
print(f"{13*'-'} create by essalhi MEKuroko007 {12*'-'}")
print(f"{20*'-'} version 1.0 {20*'-'}")
print("")
m_ip=execute('ifconfig eth0 | grep "inet" ') 
m_ip=m_ip.decode('utf-8').strip().split(" ")[1]
print(f"[+] your ip is : {m_ip}")
print(52*"-" + "!")
octets=".".join(m_ip.split(".")[:-1])
subnet=octets+".0/24"
print(f"[+] your network is : {subnet}")
print(53*"-")
print("[+] running netdiscover ......")
ips=execute('netdiscover -P -r %s |grep "1" | cut -d " " -f 2 ' % subnet).decode('utf-8').splitlines()

for i in range(0,len(ips)):
        ip=ips[i]
        print(f"[{i+1}] {ip}")
choice= int(input(f"\nEnter your choice , from 1 to {len(ips)} or enter 0 to exit : "))
if choice == 0 :
        exit()
else : 
        print(" ")
        print(f"[+] your choice is {ips[choice - 1]}")
print(20*"!-!-")
print(" ")
try :
        print (nmap_scan(ips[choice - 1]))
except :
        pass
